let contacts = [
    {
        name:"instagram",
        link:"https://www.instagram.com/srbmaury/",
    },
    {
        name:"facebook",
        link:"https://m.facebook.com/profile.php?id=100057795465187",
    },
    {
        name:"gmail",
        link:"mailto:saurabh.maurya.ece20@gmail.com",
    },
    {
        name:"linkedin",
        link:"https://www.linkedin.com/in/saurabh-maurya-39b04b205",
    },
    {
        name:"twitter",
        link:"https://mobile.twitter.com/SrbMaury",
    },
    {
        name:"github",
        link:"https://github.com/srbmaury",
    }
]